#!/usr/bin/env node

'use strict';

var fs = require('fs'),
    help = require('./libs/help'),
    commands = process.argv.slice(2);

//check to see if any params are set
if (commands.length === 0 || commands[0] === '-h') {
    help.execute();
}

//compare params to lib files
fs.exists(__dirname + '/libs/'+ commands[0] + '.js', function (exists) {
    var command;
    if(exists) {
        command = require(__dirname + '/libs/'+ commands[0] + '.js');
        command.execute();
    } else {
        help.execute();
    }
});
